### ISSUE TITLE
Input pins of type 'path' seem to change drive letter according to the drive the patch is saved on

### ISSUE THREAD

**Issue by everyoneishappy** [vvvv/VL.StandardLibs#117]
Seems the drive letter is being swapped out with whatever drive the patch is saved on.  This *seems* to be a distinct and unwanted behavior from relative vs absolute paths. 

[DrivePathBugDemo.zip](https://github.com/vvvv/VL.Stride/files/7878667/DrivePathBugDemo.zip)

**Comment by joreg** [comment]
sorry for late. the issue at hand is actually that IOBoxes simply don't support absolut paths but hide that fact quite efficiently. i've added info on how to work around this here: https://thegraybook.vvvv.org/reference/language/ioboxes.html#paths
