### ISSUE TITLE
`TableGetSortSpecs` throws an Error, when Table hasn't Sortable Flag.

### ISSUE THREAD

**Issue by antongit** [vvvv/VL.StandardLibs#25]
The Idea from @azeno was, that the Table should write to the Context if it has the `Sortable` Flag set and the `TableGetSortSpecs` should check it first.

Testpatch:
[Imgui_TableGetSortSpecs_Error.zip](https://github.com/vvvv/VL.StandardLibs/files/11026037/Imgui_TableGetSortSpecs_Error.zip)

**Comment by azeno** [comment]
Thanks. Fix was straight forward, simply doing a null check. The above commit also adds a missing forward for the specs, and ensures the output spread doesn't change as long as the specs don't change.
