### ISSUE TITLE
`FontStyle` Enum mismatch

### ISSUE THREAD

**Issue by antongit** [vvvv/VL.StandardLibs#620]
**Describe the bug**
Wrong type of the `FontStyle` Enum.

**Which version are you experiencing the bug with?**
5.0-preview0676

**Is there an earlier version where this still works?**
no

**To Reproduce**
Try to make an IOBOX (enum) for the `FontStyle` pin

**Screenshots**
![image](https://user-images.githubusercontent.com/1189037/222432390-06c4cf08-5a46-43ae-beba-bf2046932110.png)

**Comment by azeno** [comment]
Thanks. Type forward was missing.
