### ISSUE TITLE
`Pipet` / `Readback` nodes should avoid blocking at all cost

### ISSUE THREAD

**Issue by azeno** [vvvv/VL.StandardLibs#624]
**Describe the bug**
The current `ReadBackBuffer` node which is used by nodes such as `Pipet` or `TextureToImage` can cause severe frame rate issues once it starts blocking. Also note that `TextureToImage` is used by our IO boxes and tooltips.

**Which version are you experiencing the bug with?**
5.0-preview735

**Is there an earlier version where this still works?**
5.0-preview588

**To Reproduce**
See attached patch

**Expected behavior**
These nodes shouldn't block at all. If that is needed for some reason then they should use an input pin to do so.

**Additional context**
This issue surfaced recently in a project. Initially we thought it's the switch of Stride from the old swap chain blt model to the more performant flip model. But as it turns out stalling the GPU by doing a blocking read on it seems to have a different effect on a flip based swap chain than on a blt based one. In any case, one should avoid a block in all cases.

[BlockingPipetCausesInstableFPS.zip](https://github.com/vvvv/VL.StandardLibs/files/11122726/BlockingPipetCausesInstableFPS.zip)

**Comment by azeno** [comment]
As an alternative we could also add a Warn node to the ReadBackBuffer when it blocks. However I still believe that the approach taken in NDI is better, it uses a dynamic queue structure internally to setup the right amount of staging textures.

**Comment by tebjan** [comment]
The buffer readback is just a copy of strides image readback and should be PRed back to the main repo: [ImageReadback.cs](https://github.com/stride3d/stride/blob/master/sources/engine/Stride.Rendering/Rendering/Images/ImageReadback/ImageReadback.cs)

if it can work adaptively (or is it already and the delay setting is just a max delay setting?) then that would be much better of course can also be merged back to stride.

**Comment by azeno** [comment]
Just looked it up, and indeed it uses a maximum (which is also set too low btw) - https://github.com/vvvv/VL.StandardLibs/blob/main/VL.Stride.Runtime/src/Video/TextureToVideoStream.cs#L70

But since its a maximum we could set it higher (like 16) without having to fear the default causes the data to be too outdated.
