### ISSUE TITLE
Channels: proposing GetSlice [Reactive.Channel]

### ISSUE THREAD

**Issue by antongit** [vvvv/VL.StandardLibs#628]
**Is your feature request related to a problem? Please describe.**
There is no easy way to convert between human-readable-strings and datatypes when binding.
An example is ImGui's `Combo` (dropdown). UI shows Strings, but the logic is interested in the "values" behind them.
(see the screenshot, where the Strings are mapped to Vector2s).

**Describe the solution you'd like**
One can use Merge (Selector), but it's cumbersome.
GetSlice [Reactive.Channel] offers an easy mapping of Strings (as an example) to Index, and the Index is then used to choose the "value".

Although GetSlice can be a good old name, it is working with Channels so shouldn't be confused with the old one.
Maybe it is still not the best name.

Invented with @gregsn but the node still needs more thoughts about namings.

![image](https://user-images.githubusercontent.com/1189037/231224827-9a61d465-2743-49fb-aef2-ef3105adc3a4.png)

[GetSlice Channel.zip](https://github.com/vvvv/VL.StandardLibs/files/11202638/GetSlice.Channel.zip)

**Comment by gregsn** [comment]
b96c90be7e3f6f6dc7751e3f09484abb74258bc0
