### ISSUE TITLE
Ping [IO.Net] leads to Pause on F9

### ISSUE THREAD

**Issue by antongit** [vvvv/VL.StandardLibs#642]
**Describe the bug**
Pressing F9 leads to pause sometimes.
In a bigger setup the Pause follows on every F9 and won't recover.
Is it only me?

**Which version are you experiencing the bug with?**
5.3-preview0018

**To Reproduce**
1. Start attached patch
2. Click F9 several times. Fast or slow. Sometimes I've got pause

**Expected behavior**
No Pause.

[Ping_Bug.zip](https://github.com/vvvv/VL.StandardLibs/files/11847943/Ping_Bug.zip)

**Comment by joreg** [comment]
the error it jumps to for me is this:

**Comment by gregsn** [comment]
was a runtime/compiler bug
