### ISSUE TITLE
Add GaussianSpread

### ISSUE THREAD

**Issue by tebjan** [vvvv/VL.StandardLibs#653]
**Is your feature request related to a problem? Please describe.**
Extending generative design capabilities by random values with Gaussian distribution.

**Describe the solution you'd like**
Add these nodes to the Lib: https://github.com/bj-rn/VL.Addons/issues/9

**Describe alternatives you've considered**
Add them to VL.Addons.

**Additional context**
Nodes and help patch are already patched:

![image](https://github.com/vvvv/VL.StandardLibs/assets/1094716/3c9b2ba5-b008-46bf-a374-9b8dd0644630)

**Comment by azeno** [comment]
Thanks a lot! Merged.
