### ISSUE TITLE
[VL.IO.Redis] 

### ISSUE THREAD

**Issue by kopffarben** [vvvv/VL.StandardLibs#659]
- documentation transactional workflow
- Error Handeling

**Comment by joreg** [comment]
Serialization:
- [ ] Client has "Serializer" input with entries: "MsgPack, JSon, None", defaulting to "MsgPack"
- [ ] Binding node has "Serializer" input with entries "Default, MsgPack, JSon, None", defaulting to "Default"
- [ ] Binding node throws exception in case of "None" when the type is not supported

**Comment by azeno** [comment]
Initialization bugger: https://github.com/vvvv/VL.StandardLibs/pull/662#issuecomment-1801718472

**Comment by antongit** [comment]
Placing `RadisModule` without redisbackend installed leads to a long complete freeze followed by a pink node.
