### ISSUE TITLE
Type constraint in ShaderFX prevents arbitrary shader composition

### ISSUE THREAD

**Issue by tebjan** [vvvv/VL.StandardLibs#665]
**Describe the bug**
The type constraint `unmanaged` prevents arbitrary shader-type compositions.

**Which version are you experiencing the bug with?**
5.3-preview334

**Is there an earlier version where this still works?**
5.2

**To Reproduce**
build a shader graph with a custom shader type, not using known types, like ComputeFloat4 etc.

```c
shader CustomShaderNode_ShaderFX : CustomShaderType
{

};

shader CustomShaderNodeConsumer_ShaderFX : CustomShaderType
{
    compose CustomShaderType MyCostomUpstreamShader;
};
```

**Expected behavior**
Shader graph works as before, arbitrary shader types can be composed, not only known ones.

**Screenshots**
<img width="742" alt="image" src="https://github.com/vvvv/VL.StandardLibs/assets/1094716/586588a7-25bc-4466-8fb7-5cdb1b74e671">

**Comment by azeno** [comment]
Thanks, this was not intended of course. Reverted most of that commit except the part which adds the constraint to the `T -> Gpu<T>` implicit linking.

**Comment by tebjan** [comment]
There would also be the fix that would change the helper type `VoidOrUnknown` to `struct`, I've done that temporarily to get it working. I didn't check whether the HLSL return types must always be blittable types. I never tried to return Texture or Buffer from a HLSL method. If it doesn't work to return resources/objects the managed constraint would probably be ok.
